### ISSUE TITLE
Webhook doesn't work

### ISSUE THREAD

**Issue by nanoyan** [skohub-io/skohub-vocabs#303] opened 2024-05-08 06:25 UTC
Our repository https://github.com/iqb-vocabs/v25 has the same content as 3 weeks ago. Yesterday we made a minor update in one Vocabulary, somehow we can get an error on the payload. We rollback to the same content and the payload also failed.
Are there new requirements? Thank you

**Comment by acka47** [comment] 2024-05-08 06:55
Hi @nanoyan , thanks for the report. Generally, there have been some changes but off the top of my head I am not aware of any tighter restrictions. Could you provide the URL to the SkoHub build log, please, so that we can investigate?

**Comment by nanoyan** [comment] 2024-05-08 07:18
Hi @acka47, thank you for quick answer.  https://skohub.io/build?id=d4f9b1da-06ad-4e1b-b49a-776f97fc05bd
Thank you,
Yan

**Comment by nanoyan** [comment] 2024-05-08 08:58
Hi Adrian @acka47, I found the reason why our ttl didn't work. A commit of two weeks ago, skohub made obligatory to have @prefix dc: <http://purl.org/dc/elements/1.1/> . and dc:title and dc:description. And our vocabulary only had dct:title. 
Our Vocabulary is online again.
Thank you for quick reaction and have a nice day.
Yan

**Comment by acka47** [comment] 2024-05-08 09:11
> A commit of two weeks ago, skohub made obligatory to have @Prefix dc: http://purl.org/dc/elements/1.1/ . and dc:title and dc:description. And our vocabulary only had dct:title.

To me knowledge, this should not be the cause of a problem. We have only added the option to use `skos:prefLabel`, `dc:title`., `dc:creator` and `dc:descriptiuon`. Vocabs without those should still work (and do work, see e.g. https://w3id.org/kim/hcrt/scheme). So, I guess the cause of the problem was something else. Do you have a link to the turtle version of the vocab in question?

**Comment by acka47** [comment] 2024-05-08 09:15
I assume the vocabs should be online at https://skohub.io/iqb-vocabs/v25/heads/master/, shouldn't they? I am reopening as I would like to understand the problem better.

**Comment by nanoyan** [comment] 2024-05-08 09:26
Yes, the https://skohub.io/iqb-vocabs/v25/heads/master/ are online and works. Sometimes we make changes to our existing vocabulary, by adding or deleting concept. And we the last time I deleted a skos:concept, it made our offline. An now I added manually  @prefix skos: <http://www.w3.org/2004/02/skos/core#>. to our ttl and replace skos:ConceptScheme dct: title to dc:title and dc:description. It apparently solves the problem.

**Comment by acka47** [comment] 2024-05-08 09:50
Ah, ok. If ` @prefix skos: http://www.w3.org/2004/02/skos/core#` was missing then the vocab would not build. However, as mentioned above, it is not obligatory to use `dc:title` and `dc:description`, you can also use `dct:title` and `dc:description`. Closing

**Closed by acka47** 2024-05-08 09:50 UTC
